theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
title: Deus-X:~#
description: Offensive for Defensive!.
show_downloads: false
show_repo: false

safe: true

plugins:
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

